USE [MASTER]
CREATE DATABASE ExCoreODS;
ALTER DATABASE ExCoreODS SET RECOVERY SIMPLE;
CREATE LOGIN ExCoreODSUser WITH PASSWORD = 'ExCoreODSPass', DEFAULT_DATABASE = [ExCoreODS], DEFAULT_LANGUAGE = ENGLISH, CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF;
GO
USE [ExCoreODS]
CREATE USER [ExCoreODSUser] FOR LOGIN [ExCoreODSUser];
GO
CREATE SCHEMA [ExCoreODSSchema] AUTHORIZATION [ExCoreODSUser];
GO
ALTER USER [ExCoreODSUser] WITH DEFAULT_SCHEMA=[ExCoreODSSchema];
GO
GRANT ALTER, ALTER ANY SCHEMA, AUTHENTICATE, BACKUP DATABASE, BACKUP LOG, CHECKPOINT, CONNECT, CONTROL, CREATE DEFAULT, CREATE FUNCTION, CREATE PROCEDURE, CREATE SCHEMA, CREATE SYNONYM, CREATE TABLE, CREATE TYPE, CREATE VIEW, DELETE, EXECUTE, INSERT, REFERENCES, SELECT, SHOWPLAN, TAKE OWNERSHIP, UPDATE, VIEW DATABASE STATE, VIEW DEFINITION TO [ExCoreODSUser];
GO
USE [msdb]
CREATE USER [ExCoreODSUser] FOR LOGIN [ExCoreODSUser]
ALTER USER [ExCoreODSUser] WITH DEFAULT_SCHEMA=[dbo]
ALTER ROLE [SQLAgentUserRole] ADD MEMBER [ExCoreODSUser]
GRANT SELECT ON msdb.[dbo].[sysjobs] TO [ExCoreODSUser]
GRANT SELECT ON msdb.[dbo].[sysjobs_view] TO [ExCoreODSUser]
GRANT SELECT ON msdb.[dbo].[sysjobhistory] TO [ExCoreODSUser]
GRANT SELECT ON msdb.[dbo].[sysjobactivity] TO [ExCoreODSUser]
GO